service: backlog-api-rate-monitoring

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  timeout: 900
  iamManagedPolicies:
    - 'arn:aws:iam::aws:policy/CloudWatchFullAccess'
    - 'arn:aws:iam::aws:policy/AWSLambdaExecute'

functions:
  monitor:
    handler: handler.main
    events:
      - schedule: rate(1 minute)
    environment:
      backlog_space_key: ${opt:backlog_space_key}
      backlog_api_key_list: ${opt:backlog_api_key_list}
      monitoring_period: 5
      monitoring_count: 12

plugins:
  - serverless-python-requirements
